#!/bin/bash
# copy only needed ".py" files to each pi node
# scp -r ../lyricsearch pi@193.168.1.11:/home/pi # pi1
scp src/*.py pi@192.168.1.11:/home/pi/lyricsearch/src
scp src/*.py pi@192.168.1.12:/home/pi/lyricsearch/src
scp src/*.py pi@192.168.1.13:/home/pi/lyricsearch/src
scp src/*.py pi@192.168.1.14:/home/pi/lyricsearch/src
